kind: Deployment
apiVersion: apps/v1

metadata:
  name: myapp-deployment
  namespace: myns
  labels: 
      app: myapp-deployment
      version: v1

spec: 
  replicas: 4
  selector:
    matchLabels:
      app: myapp-pod
      version: v1
  template: 
    metadata:
      name: myapp-pod
      labels: 
        app: myapp-pod
        version: v1
    spec:
        containers:
        - name: myapp
          image: stackupiss/northwind-app:v1
          imagePullPolicy: Always
          ports:
          - name: myapp-port
            containerPort: 3000