kind: ServiceAccount
apiVersion: v1

metadata:
   name: tiller-myns
   namespace: myns

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
   name: tiller-myns-crb
   namespace: myns

roleRef:
   apiGroup: rbac.authorization.k8s.io
   kind: ClusterRole
   name: admin

subjects:
- kind: ServiceAccount
  name: tiller-sa
  namespace: myns
