kind: Service
apiVersion: v1

metadata:
  name: mydb-svc
  namespace: myns
  labels: 
      app: mydb-svc
      version: v1
spec: 
  type: ClusterIP 
  selector:
    app: mydb-pod
  ports:
  - name: mydb-svc-port
    port: 3
    targetPort: mysql-port